package app.tweet.entity;
// Generated 2019/02/11 17:54:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TsComment generated by hbm2java
 */
@Entity
@Table(name = "ts_comment")
public class TsComment implements java.io.Serializable {

	private int commentId;
	private Integer commentUserId;
	private Integer commentPostId;
	private String comment;
	private Date commentTs;

	public TsComment() {
	}

	public TsComment(int commentId, String comment) {
		this.commentId = commentId;
		this.comment = comment;
	}

	public TsComment(int commentId, Integer commentUserId, Integer commentPostId, String comment, Date commentTs) {
		this.commentId = commentId;
		this.commentUserId = commentUserId;
		this.commentPostId = commentPostId;
		this.comment = comment;
		this.commentTs = commentTs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "comment_id", unique = true, nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	@Column(name = "comment_user_id")
	public Integer getCommentUserId() {
		return this.commentUserId;
	}

	public void setCommentUserId(Integer commentUserId) {
		this.commentUserId = commentUserId;
	}

	@Column(name = "comment_post_id")
	public Integer getCommentPostId() {
		return this.commentPostId;
	}

	public void setCommentPostId(Integer commentPostId) {
		this.commentPostId = commentPostId;
	}

	@Column(name = "comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_ts", length = 29)
	public Date getCommentTs() {
		return this.commentTs;
	}

	public void setCommentTs(Date commentTs) {
		this.commentTs = commentTs;
	}

}
