package app.tweet.entity;
// Generated 2019/02/17 14:30:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.tweet.base.BaseEntity;

/**
 * TsNotification generated by hbm2java
 */
@Entity
@Table(name = "ts_notification")
public class TsNotification extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int notificationId;
	private String notificationType;
	private Integer notificationUserFromId;
	private Integer notificationUserToId;
	private Integer notificationPostId;
	private Date notificationTs;

	public TsNotification() {
	}

	public TsNotification(int notificationId) {
		this.notificationId = notificationId;
	}

	public TsNotification(int notificationId, String notificationType, Integer notificationUserFromId,
			Integer notificationUserToId, Integer notificationPostId, Date notificationTs) {
		this.notificationId = notificationId;
		this.notificationType = notificationType;
		this.notificationUserFromId = notificationUserFromId;
		this.notificationUserToId = notificationUserToId;
		this.notificationPostId = notificationPostId;
		this.notificationTs = notificationTs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "notification_id", unique = true, nullable = false)
	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "notification_type", length = 30)
	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	@Column(name = "notification_user_from_id")
	public Integer getNotificationUserFromId() {
		return this.notificationUserFromId;
	}

	public void setNotificationUserFromId(Integer notificationUserFromId) {
		this.notificationUserFromId = notificationUserFromId;
	}

	@Column(name = "notification_user_to_id")
	public Integer getNotificationUserToId() {
		return this.notificationUserToId;
	}

	public void setNotificationUserToId(Integer notificationUserToId) {
		this.notificationUserToId = notificationUserToId;
	}

	@Column(name = "notification_post_id")
	public Integer getNotificationPostId() {
		return this.notificationPostId;
	}

	public void setNotificationPostId(Integer notificationPostId) {
		this.notificationPostId = notificationPostId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "notification_ts", length = 29)
	public Date getNotificationTs() {
		return this.notificationTs;
	}

	public void setNotificationTs(Date notificationTs) {
		this.notificationTs = notificationTs;
	}

}
