package app.tweet.entity;
// Generated 2019/02/17 14:30:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TsShareId generated by hbm2java
 */
@Embeddable
public class TsShareId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int shareUserId;
	private int sharePostId;

	public TsShareId() {
	}

	public TsShareId(int shareUserId, int sharePostId) {
		this.shareUserId = shareUserId;
		this.sharePostId = sharePostId;
	}

	@Column(name = "share_user_id", nullable = false)
	public int getShareUserId() {
		return this.shareUserId;
	}

	public void setShareUserId(int shareUserId) {
		this.shareUserId = shareUserId;
	}

	@Column(name = "share_post_id", nullable = false)
	public int getSharePostId() {
		return this.sharePostId;
	}

	public void setSharePostId(int sharePostId) {
		this.sharePostId = sharePostId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsShareId))
			return false;
		TsShareId castOther = (TsShareId) other;

		return (this.getShareUserId() == castOther.getShareUserId())
				&& (this.getSharePostId() == castOther.getSharePostId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getShareUserId();
		result = 37 * result + this.getSharePostId();
		return result;
	}

}
